title: Witness & Wonder
description: A collection of inspiring testimonies
theme: minima

# Build settings
markdown: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  testimonies:
    output: true
    permalink: /:slug/
