title: Witness & Wonder
description: A collection of inspiring testimonies
theme: minima

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  testimonies:
    output: true
    permalink: /:slug/

defaults:
  - scope:
      path: ""
      type: testimonies
    values:
      layout: testimony
