title: My Testimony Blog
description: A collection of inspiring testimonies
baseurl: "/"
url: "https://witness-and-wonder.github.io"
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
